### ISSUE TITLE
XTTS can only generate text with a maximum of 400 tokens

### ISSUE THREAD

**Issue by bretthysuik** [aedocw/epub2tts#161]
```
Error:  ❗ XTTS can only generate text with a maximum of 400 tokens. ... Retrying (1 retries left)
Error:  ❗ XTTS can only generate text with a maximum of 400 tokens. ... Retrying (0 retries left)
Something is wrong with the audio (97): temp3.wav
 
Traceback (most recent call last):
  File "/home/bretthy/epub2tts/.venv/bin/epub2tts", line 33, in <module>
    sys.exit(load_entry_point('epub2tts==2.2.14', 'console_scripts', 'epub2tts')())
  File "/home/bretthy/epub2tts/.venv/lib/python3.10/site-packages/epub2tts.py", line 681, in main
    mybook.read_book(
  File "/home/bretthy/epub2tts/.venv/lib/python3.10/site-packages/epub2tts.py", line 473, in read_book
    temp = AudioSegment.from_wav(tempwav)
  File "/home/bretthy/epub2tts/.venv/lib/python3.10/site-packages/pydub/audio_segment.py", line 808, in from_wav
    return cls.from_file(file, 'wav', parameters=parameters)
  File "/home/bretthy/epub2tts/.venv/lib/python3.10/site-packages/pydub/audio_segment.py", line 651, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "/home/bretthy/epub2tts/.venv/lib/python3.10/site-packages/pydub/utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'temp3.wav'
```

The text that causes the problem, specifically the long string of numbers:

```
At that moment, there was a buzz as one of the monitors turned itself on. As they watched, the screen rapidly filled with numbers:

0003212525263203262930132104261037183016061
808213229033005182204261013083016213716040
83016211822033013130432000321252526320326
293013210426103718301606180821322903300518
220426101308301623711604083016211822033013
1304320003212525263203262932104261037183016
0618082132290330051822042610130830162137
16040830162118220330131304320003212525263
203262930132104261037183016061808213229033
005182204261013083016213716040830162118220
3301313043200032125252632032629301321042610
3718301606180821322903300518220426101308
301621371604083162118220330131304320003212
525263203262930132104261037183016061808213
229033005182204261013083016213716040830162

"Where's that coming from?" Ted said. "The surface?"

Barnes shook his head. "We've cut direct contact with the surface."
```

**Comment by aedocw** [comment]
OK I understand what's happening here. TTS appears to lump all those numbers together which results in a 642 character long string. The number of tokens that breaks down to is (as far as I understand) not possible to calculate in advance, so you can't know you're sending something that creates too many tokens until after you send it.

That seems like it would be pretty terrible to listen to even if you could get it to accept the whole string... One easy option is to detect strings of numbers that are long (like ... > 50 characters?) and replace them with the text "long string of numbers". I feel like that might be kind of odd to do, but on the other hand I honestly can't think of a case where I would want to listen to 642 numbers read in a row.

Chunking every sentence down to smaller number of characters won't fix this, as I believe a number string like this gets turned into a string like "zero zero zero one two one three nine", which means it would be tricky to try to predict how small to make each chunk. I was able to run this by adding a period and line-break at the end of each of those number strings at least, so breaking up number strings at a length of 40 would work. Automating that without causing odd side-effects could be difficult though.

Per [this discussion](https://github.com/aedocw/epub2tts/discussions/158) I am working on making a workflow that would allow you to easily export the book to text, modify the text (by replacing that number block with text, or just removing it), then create the audiobook from text file *WITH* chapter breaks similar to when creating a book from epub. It might be a few days before I work on that and get a first pass created, but short of modifying your source material yourself, that's probably going to be the easiest way to solve this.

**Comment by aedocw** [comment]
Oh my it is even funnier than I realized :)

[This is the output](https://drive.google.com/file/d/1mGF5CsMJ3Guhs5aruNtEgpFavOuj2cgM/view?usp=sharing) from the first two lines of numbers, with a period and line-break added.

The script should not be making editorial decisions, so I do not think I can add logic to automatically handle strings of numbers this long. BUT making it relatively easy for the user to edit the content before feeding it in to be turned into an audiobook leaves decisions like that up to the user, which seems pretty reasonable to me.

When I start working on the text-export branch I will link it to this issue so you can follow along or pull down and test as it progresses.

**Comment by bretthysuik** [comment]
> making it relatively easy for the user to edit the content before feeding it in to be turned into an audiobook leaves decisions like that up to the user, which seems pretty reasonable to me.

Agreed. This particular book has quite a few instances of this and being able to edit the input text file should solve the problems. Here's some more examples:


```
"Here's a copy of the original sequence," Tina said, handing them a sheet.

00032125252632 032629 301321 04261037 18 3016 06180821
32 29033005 1822 04261013 0830162137 1604 08301621 1822 0
33013130432

"Good," Harry said. "Now you can see my problem at once. Look at the word: oh-oh-oh-three-two-one, and so on. The question is, how do I break that word up into individual letters? I couldn't decide, but now I know."
```

```
"You mean a picture?"

"Yes," Ted said. "And I think it's a picture of the creature itself!" He started searching through sheets of paper. "I started with this."

001110101110011100111010100000    111101011101
   11110110110101    100110101010100101
100101111010000     11010010100010101100000
111011111110101     1001010110      1001101010101101
      1000111101000010101100101     10000100
1000111101000010101      1001010110
111111011011101100100000
001110101110011100111010100000     111101011101
11110110110101     100110101010100101      10010
1111010000      11010010100010101100000
111011111110101      1001010110      1001101010101101
     1000111101000010101100101       10000100
1000111101000010101     1001010110
111111011011101100100000
001110101110011100111010100000     111101011101
   11110110110101      100110101010100101      10010
   1111010000      11010010100010101100000
111011111110101      1001010110      1001101010101101
      1000111101000010101100101      10000100

"Now, here I have translated the message to binary," Ted said. "You can immediately sense visual pattern, can't you?"
```

```
"Well, it is certainly suggestive," Ted said. "I'm telling you, all those years at JPL looking at images from the planets, I have an eye for these things. So, the next thing I did was go back to the original message and fill in the spaces. I got this."

• •00032125252632• •032629• •301321• •04261037• •18•
•3016• •0618082132• •29033005• •1822• •04261013•
•0830162137• •1604• •08301621• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037• •18•
•3016• •0618082132• •29033005• •1822• •04261013•
•0830162137• •1604• •08301621• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037• •18•
•3016• •0618082132• •29033005• •1822• •04261013•
•0830162137• •1604• •08301621• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037• •18•
•3016• •0618082132• •29033005• •1822• •04261013•
•0830162137• •1604• •08301621• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037• •18•
•3016• •0618082132• •29033005• •1822• •04261013•
•0830162137• •1604• •08301621• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037• •18•
•3016• •0618082132• •29033005• •1822• •04261013•
•0830162137• •1604• •08301521• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037• •18•
•3016• •0618082132• •29033005• •1822• •04261013•
•0830162137• •1604• •08301621• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037• •18•
•3016• •0618082132• •29033008• •1822• •04261013•
•0830162137• •1604• •08301621• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037• •18•

"Uh-huh . . ." Norman said.

"I agree, it doesn't look like anything," Ted said. "But by changing the screen width, you get this."

Proudly, he held up the next sheet.

• •00032125252632• •032629• •301321•
•04261037• •18• •3016• •0618082132• •29033005•
•1822• •042610134• •0830162137• •1604•
•08301621• •1822• •033013130432•
•00032125252632• •032629• •301321• •04261037•
•18• •3016• •0618082132• •29033005• •1822•
•04261013• •0830162137• •1604• •08301621•
•1822• •033013130432• •00032125252632•
•032629• •301321• •04261037• •18• •3016•
•0618082132• •29033005• •1822• •04261013•
•0830162137• •1604• •08301621• •1822•
•033013130432• •00032125252632• •032629•
•301321• •04261037• •18• •3016• •0618082132•
•29033005• •1822• •04261013• •0830162137•
•1604• •08301621• •1822• •033013130432•
•00032125252632• •0326294, •301321• •04261037•
•18• •3016• •0618082132• •29033005• •1822•
•04261013• •0830162137• •1604• •08301621•
•1822• •033013130432• •00032125252632•
•032629• •301321• •04261037• •18• •3016•

"Yes?" Norman said.

"Don't tell me you don't see the pattern," Ted said.
```

**Comment by aedocw** [comment]
This was automatically closed when I merged in the last piece of the export/edit/record workflow.

Please give it a try, just do `epub2tts mybook.epub --export txt`, make your modifications, then do `epub2tts mybook.txt` (along with any other options.)

Even though this issue is closed, please let me know if this works out for you. Good luck!
