### ISSUE TITLE
"Unable to import torch" error on Windows

### ISSUE THREAD

**Issue by alexnev** [aedocw/epub2tts#218]
I've installed torch but it still gives the same error, i dont know what to do, please help. I'm on Windows 10

```
(.venv) PS C:\epub2TTS\epub2tts> pip install .
Processing c:\epub2tts\epub2tts
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting beautifulsoup4 (from epub2tts==2.3.15)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting deepspeed (from epub2tts==2.3.15)
  Using cached deepspeed-0.14.0.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
      [93m [WARNING] [0m unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "C:\epub2TTS\epub2tts\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\epub2TTS\epub2tts\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\epub2TTS\epub2tts\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\D\AppData\Local\Temp\pip-build-env-wgt952dy\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\D\AppData\Local\Temp\pip-build-env-wgt952dy\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\D\AppData\Local\Temp\pip-build-env-wgt952dy\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\D\AppData\Local\Temp\pip-build-env-wgt952dy\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 148, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by aedocw** [comment]
Could you try `pip install torch==2.1.1` in that same virtual env and see what you get?

I should lock down the versions of all the dependencies, I'd like to do that with pipenv but I haven't had time to get to that. Wondering if there's a newer release of torch that is causing some dependency problems... If the torch installed pinned to 2.1.1 works but you hit other issues, at least it can help point us in the right direction.

**Comment by aedocw** [comment]
Could you try editing requirements.txt and removing the "deepspeed" line? I tried on windows 11 and that was what was causing the problem. I am not sure why deepspeed won't install, maybe someone else who is running this on windows can chime in on that. But without deepspeed, the install went great for me, let me know if it works for you.

**Comment by aedocw** [comment]
Closing due to lack of response. If other people are hitting the same error on windows please mention it here and I'll re-open, and try running on windows.
