### ISSUE TITLE
Error using epub source and default settings

### ISSUE THREAD

**Issue by aedocw** [aedocw/epub2tts#239]
Using version `2.4.2` with the following command:
`epub2tts Downloads/mybook.epub`

I got this error:
```
Traceback (most recent call last):
  File "/Users/doc/repos/epub2tts/.venv/bin/epub2tts", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/doc/repos/epub2tts/.venv/lib/python3.11/site-packages/epub2tts.py", line 902, in main
    mybook.read_book(
  File "/Users/doc/repos/epub2tts/.venv/lib/python3.11/site-packages/epub2tts.py", line 604, in read_book
    f"Something is wrong with the audio ({ratio}): {tempwav}"
                                          ^^^^^
UnboundLocalError: cannot access local variable 'ratio' where it is not associated with a value
```

**Comment by aedocw** [comment]
Really weird, but now I cannot reproduce, so closing.
