### ISSUE TITLE
problem after update to 2.4.6

### ISSUE THREAD

**Issue by rejuce** [aedocw/epub2tts#261]
i updated to v 2.4.6, isntall was succesfull on ubuntu 22.04 WSL

after that, the same command that was still working yesterday fails with taht error:

Installing collected packages: epub2tts
  Attempting uninstall: epub2tts
    Found existing installation: epub2tts 2.4.6
    Uninstalling epub2tts-2.4.6:
      Successfully uninstalled epub2tts-2.4.6
Successfully installed epub2tts-2.4.6
jk@GMNB-0036:~/epub2tts$ cd ../epubconvert/tate/
jk@GMNB-0036:~/epubconvert/tate$ python3 /home/jk/epub2tts/epub2tts.py Tate-no-Yuusha-no-Nariagari-_Compiled_.epub --engine xtts --speaker "Badr Odhiambo" --skiplinks
/home/jk/epub2tts/epub2tts.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Namespace(sourcefile='Tate-no-Yuusha-no-Nariagari-_Compiled_.epub', engine='xtts', xtts=None, openai=None, model='tts_models/en/vctk/vits', speaker='Badr Odhiambo', scan=False, start=1, end=999, language='en', minratio=88, skiplinks=True, skipfootnotes=False, sayparts=False, audioformat='m4b', bitrate='69k', debug=False, export=None, no_deepspeed=False, skip_cleanup=False, cover=None)
Traceback (most recent call last):
  File "/home/jk/epub2tts/epub2tts.py", line 962, in <module>
    main()
  File "/home/jk/epub2tts/epub2tts.py", line 905, in main
    mybook = EpubToAudiobook(
  File "/home/jk/epub2tts/epub2tts.py", line 107, in __init__
    self.ensure_punkt()
  File "/home/jk/epub2tts/epub2tts.py", line 115, in ensure_punkt
    nltk.data.find("tokenizers/punkt_tab")
  File "/home/jk/.local/lib/python3.10/site-packages/nltk/data.py", line 537, in find
    return FileSystemPathPointer(p)
  File "/home/jk/.local/lib/python3.10/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/jk/.local/lib/python3.10/site-packages/nltk/data.py", line 312, in __init__
    raise OSError("No such file or directory: %r" % _path)
OSError: No such file or directory: '/home/jk/nltk_data/tokenizers/punkt/PY3_tab'

**Comment by rejuce** [comment]
i downgraded to commit 5f9ffda 2.4.5 and it worked again

**Comment by erictbar** [comment]
Got the same error, ran `pip install --upgrade nltk` and it got past that point and has started the task.

(Referenced https://github.com/nltk/nltk/issues/3305)
