### ISSUE TITLE
Updated to most recent changes and now getting the error: ValueError:  [!] Model file not found in the output path

### ISSUE THREAD

**Issue by Lastofthefirst** [aedocw/epub2tts#284]
I'm on linux debian, using conda.

```
epub2tts /home/quddus/sd/epub2tts/Carl_Schmitt.txt --speaker p307


Namespace(sourcefile='/home/quddus/sd/epub2tts/Carl_Schmitt.txt', engine='tts', xtts=None, openai=None, model='tts_models/en/vctk/vits', speaker='p307', scan=False, start=1, threads=2, end=999, language='en', minratio=88, skiplinks=False, skipfootnotes=False, sayparts=False, audioformat='m4b', bitrate='69k', debug=False, export=None, no_deepspeed=False, skip_cleanup=False, cover=None)
Language selected: en
in main, Speaker is p307
Part: 1
CARL SCHMITf
Speaker: p307
"Mass Society,"Democracy,and Public Opinion  
 
73
Part: 2
EXCERPT FROM  THE CRISIS  OF  PARLIAMENTARY DEMOCRACY  (1923)
Speaker: p307
Carl Schmitt  (1888-1985) was a  German professorof law.  He was  oneof theforemostinterpretersof the idea of the liberal Rechtsstaat,  of a rule  of  law,  as  well as oneof itsfiercest critics. Schmitt belongedto thesocalledconservativerevolutionof the W
Part: 3
Chapter 2,  The Principles of Parliamentarism
Speaker: p307
In the struggle between parliament and monarchy, a government that was decisively influenced by the representation of the people was called a parliamentary government, and the word was thus applied to a particular kind of executive. The meaning of the conc
Part: 4
1,   Openness
Speaker: p307
76  Section  II 
 
The belief in public opinion has its roots in a conception that has not been properly emphasized in the enormous literature on public opinion, not even in Tonnies's great work." It is less a question of public opinion than a question abo
Part: 5
2,  The  division (balance)  of  powers
Speaker: p307
In modem parliamentarism the belief in public opinion is bound to a second, more organizational conception,  the division or balance of different state activities and institutions. Here too the idea of competition appears, a competition from which the trut
Part: 6
3,  The  Conceptof  Law and  Legislationin Parliamentarism
Speaker: p307
The parliamentary conception of legislation is already recognizable with the Monarchomachians. In his  Droit  des  Magistrats, Beza writes,  "One should not judge by cases, but by the law."24The  Vindiciae of Junius Brutus was directed against the 
 
"pern
Part: 7
4,   ParliamentLimitedto Legislation
Speaker: p307
80  Section  II 
 
Law,  Veritas in contrast to mere  Autoritas, the generally correct norm in contrast to the merely real and concrete order as Zitelmann argued in a brilliant formulation." as an imperative always contains an individual nontransferable mo
Part: 8
5,  The GeneralMeaning of the Beliefin Discussion
Speaker: p307
Openness and discussion are the two principles on which constitutional thought and parliamentarism depend in a thoroughly logical and comprehensive system. For the sense of justice of an entire historical epoch, they seemed to be essential and indispensabl
Saving to Carl_Schmitt-p307.m4b
Total characters: 41169
Reading from 1 to 8
initiating work:
initiating chapter:  CARL SCHMITf
Traceback (most recent call last):
  File "/home/quddus/miniconda3/envs/epub2tts/bin/epub2tts", line 8, in <module>
    sys.exit(main())
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/epub2tts.py", line 1239, in main
    mybook.read_book(
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/epub2tts.py", line 941, in read_book
    map_result = list(map(process_book_chapter, chapter_job_que))
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/epub2tts.py", line 353, in process_book_chapter
    tts_engine = dat['config']['engine_cl'](dat['config'])
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/epub2tts.py", line 291, in __init__
    self.tts = TTS(self.config['model_name']).to(self.device)
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/TTS/api.py", line 75, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/TTS/api.py", line 173, in load_tts_model_by_name
    model_path, config_path, vocoder_path, vocoder_config_path, model_dir = self.download_model_by_name(model_name)
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/TTS/api.py", line 131, in download_model_by_name
    model_path, config_path, model_item = self.manager.download_model(model_name)
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/TTS/utils/manage.py", line 409, in download_model
    output_model_path, output_config_path = self._find_files(output_path)
  File "/home/quddus/miniconda3/envs/epub2tts/lib/python3.9/site-packages/TTS/utils/manage.py", line 432, in _find_files
    raise ValueError(" [!] Model file not found in the output path")
ValueError:  [!] Model file not found in the output path
```

**Comment by Lastofthefirst** [comment]
The script worked when using the xtts engine.
